sudo: required
services:
  - docker

before_install:
  - docker build -t renboy94/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true renboy94/react-test npm test

after_success:
  - docker build -t renboy94/multi-client ./client
  - docker build -t renboy94/multi-nginx ./nginx
  - docker build -t renboy94/multi-server ./server
  - docker build -t renboy94/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to the docker hub
  - docker push renboy94/multi-client
  - docker push renboy94/multi-nginx
  - docker push renboy94/multi-server
  - docker push renboy94/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-829709638192
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
